# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yitzhak's Notebook
description: > # this means to ignore newlines until "baseurl:"
  Este site foi criado para registrar anotações sobre estudos diversos.
  Sinta-se a vontade para comentar e discutir suas ideias.
baseurl: "/notebook" # the subpath of your site, e.g. /blog
url: "https://YitzhakAndrade.github.io/notebook" # the base hostname & protocol for your site
twitter_username: YitzhakAndrade
github_username:  YitzhakAndrade
medium_username:  YitzhakAndrade

# Build settings
markdown: kramdown
permalink: :year/:month/:day/:title
# highlighter: pygments
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
